apiVersion: v1
kind: Service
metadata:
  name: fss-service
spec:
  type: LoadBalancer
  ports:
      # service port in cluster
    - port: 5000
      # port to contact inside container
      targetPort: 5000
  selector:
    app: fss-deployment
